---
- hosts: node
  vars:
    result:
  tasks:
  - name: Check that a web server page returns a status 200
    shell: /etc/ansible/test.sh
    register: result
  - debug: var=result
  - name: sleep for the output of the result
    shell: "sleep 5"
