---
- hosts: node
  vars:
    result:
  tasks:
  - name: Check that a web server page returns a status 200
    shell: /etc/ansible/test.sh nginx-load-balancer
    register: result
  - debug: var=result
  - name: Output of the result
    shell: "sleep 5"
